defaultSemverRangePrefix: ''

nodeLinker: node-modules

npmPublishAccess: public

npmScopes:
  dvcorg:
    npmAuthToken: '${NODE_AUTH_TOKEN:-}'
    npmPublishRegistry: 'https://registry.npmjs.org'
    npmRegistryServer: 'https://registry.npmjs.org'

yarnPath: .yarn/releases/yarn-4.12.0.cjs
